### ISSUE TITLE
Can't scroll with keyboard keys

### ISSUE THREAD

**Issue by quozl** [sugarlabs-appstore/aslo-v4#20]
On initial loading, or when a search is made, the page can't be scrolled using the down, page down, home, end, up, or page up keys.

**Comment by srevinsaju** [comment]
Page Up, Page Down, Home and End keys work for me on the Chromium and Gecko engine.

**Comment by srevinsaju** [comment]
And also on the Browse-Activity as of `v205-11-g3f07fa5`

**Comment by quozl** [comment]
Yes, seems fixed.

**Comment by quozl** [comment]
Seems specific to Firefox.  Do you want to support Firefox?

**Comment by free-libre-software** [comment]
On page load and even after search (pressing return key), focus is on search bar. This causes the navigation keys to not work in all browsers. If we remove the focus by pressing TAB key than all navigation keys work.

**Comment by quozl** [comment]
My understanding is that regardless of keyboard focus, navigation keys can still be intercepted by a script.
