### ISSUE TITLE
Flask icon consumes CPU

### ISSUE THREAD

**Issue by quozl** [sugarlabs-appstore/aslo-v4#21]
On opening the app store in Browse, negligible CPU resources are consumed.  But if I press the slider switch next to the laboratory flask icon, CPU usage increases substantially.  I also don't know what the switch is for, and there's no mouse-over hint.

**Comment by srevinsaju** [comment]
Yes, see @shaansubbaiah 's reply to the initial release (lava lamp toggle) http://lists.sugarlabs.org/archive/sugar-devel/2020-June/058455.html. Possibly, its a feature, disabled by default. I assume @quozl  used Chromium Engine while viewing the website. Also see https://github.com/sugarlabs-appstore/aslo-v4/commit/23b8bdfb22c77dad148c75d27d4f1dd6ac1c2572.

**Comment by quozl** [comment]
Browse uses WebKit.  I'm not using Chromium Engine as far as I know, but I don't know what is underneath.
