### ISSUE TITLE
Separate version with a dash

### ISSUE THREAD

**Issue by quozl** [sugarlabs-appstore/aslo-v4#28]
On the default view, or the search results, activity versions are rendered as a white on grey text block to the right and slightly below the activity name.

I'm fine with the colours, but what I don't like is;
* [ ] losing the dash separator,
* [x] not sharing the same text baseline.

**Comment by srevinsaju** [comment]
Hmm, they share the same baseline for me
![image](https://user-images.githubusercontent.com/48695438/88959063-1661c180-d2aa-11ea-853b-2675fe28d141.png)

I personally don't like dashes, so I did not add them. Is there an alternative?

**Comment by quozl** [comment]
Are you using Browse?  This system is for use by Browse, remember.  :grin:

I don't like dashes either, but we're stuck with them in Sugar.  It was a choice made around 2007 and so much depends on it.  Our personal likes and dislikes are not relevant.

**Comment by srevinsaju** [comment]
well, shares the same baseline for me on Browse too
![image](https://user-images.githubusercontent.com/48695438/90428579-df264980-e0cc-11ea-9cda-84dbc59bc50b.png)

**Comment by srevinsaju** [comment]
Well, I can't add a dash, if I need to, I need to remove the box around the version. What do you say?

**Comment by quozl** [comment]
Okay, it's more than the baseline, it's also the way the version number is made distinct and separate, instead of being part of the name.

![tmp](https://user-images.githubusercontent.com/2936481/90476210-61b21600-e16c-11ea-903e-f30a67d31572.png)

I don't know if the box has to be removed.  That's an implementation decision.  I'm fine with removing the box though, and the grey background.

Either present the version as part of the name, or don't present the version.

As it stands, the number in the box has no obvious meaning because it is separated from the name.

**Comment by srevinsaju** [comment]
Perfect, I will just remove the version
